// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: api.proto

package apipb

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on TaskCreationEventRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *TaskCreationEventRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on TaskCreationEventRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// TaskCreationEventRequestMultiError, or nil if none found.
func (m *TaskCreationEventRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *TaskCreationEventRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for QueueId

	// no validation rules for TaskId

	// no validation rules for AccountId

	if len(errors) > 0 {
		return TaskCreationEventRequestMultiError(errors)
	}

	return nil
}

// TaskCreationEventRequestMultiError is an error wrapping multiple validation
// errors returned by TaskCreationEventRequest.ValidateAll() if the designated
// constraints aren't met.
type TaskCreationEventRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m TaskCreationEventRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m TaskCreationEventRequestMultiError) AllErrors() []error { return m }

// TaskCreationEventRequestValidationError is the validation error returned by
// TaskCreationEventRequest.Validate if the designated constraints aren't met.
type TaskCreationEventRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e TaskCreationEventRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e TaskCreationEventRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e TaskCreationEventRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e TaskCreationEventRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e TaskCreationEventRequestValidationError) ErrorName() string {
	return "TaskCreationEventRequestValidationError"
}

// Error satisfies the builtin error interface
func (e TaskCreationEventRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sTaskCreationEventRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = TaskCreationEventRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = TaskCreationEventRequestValidationError{}

// Validate checks the field values on TaskEventResponse with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *TaskEventResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on TaskEventResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// TaskEventResponseMultiError, or nil if none found.
func (m *TaskEventResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *TaskEventResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Message

	if len(errors) > 0 {
		return TaskEventResponseMultiError(errors)
	}

	return nil
}

// TaskEventResponseMultiError is an error wrapping multiple validation errors
// returned by TaskEventResponse.ValidateAll() if the designated constraints
// aren't met.
type TaskEventResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m TaskEventResponseMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m TaskEventResponseMultiError) AllErrors() []error { return m }

// TaskEventResponseValidationError is the validation error returned by
// TaskEventResponse.Validate if the designated constraints aren't met.
type TaskEventResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e TaskEventResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e TaskEventResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e TaskEventResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e TaskEventResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e TaskEventResponseValidationError) ErrorName() string {
	return "TaskEventResponseValidationError"
}

// Error satisfies the builtin error interface
func (e TaskEventResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sTaskEventResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = TaskEventResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = TaskEventResponseValidationError{}
